#!/usr/bin/env bash

set -e

#
# This script takes the name of a remote and prints its HEAD
#

if [[ "$#" -eq 1 ]]; then
    remote=$1
else
    echo "Error, usage: $(basename $0) <REMOTE>"
    exit 1
fi

# ensure the given remote name is valid
git remote get-url $remote

# check if the HEAD is present and if not, fetch it
(if ! git symbolic-ref "refs/remotes/${remote}/HEAD" 2>/dev/null 
then
    git remote set-head "${remote}" --auto
    git symbolic-ref "refs/remotes/${remote}/HEAD"
fi) | sed "s@^refs/remotes/${remote}/@@"
