#!/bin/sh
set -e

if [[ "$#" -eq 1 ]]; then
    remote=$1
    base_branch=$(git get-mainbranch $remote)
elif [[ "$#" -eq 2 ]]; then
    remote=$1
    base_branch=$2
else
    echo "Error, usage: $(basename $0) <REMOTE> [<LOCAL-BRANCH>]"
    exit 1
fi

git find-rebased ${base_branch}
git delete-merged-on-remote ${remote} ${base_branch}
